'use client'
import React, { useRef, useState } from 'react';
import styles from './transcribe.module.css'
import Button from '../components/Button'
import FileButton from '../components/FileButton';
import DownloadButton from '../components/DownloadButton';

export default function Transcribe() {

  const playButtonClick = () => {
    console.log('Play clicked!');
  };
  const contentRef = useRef();
  return (
    <div className={styles.container}>
      <div className={styles.boxStyle}>
          <p ref={contentRef}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Rhoncus mattis rhoncus urna neque viverra justo. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Justo donec enim diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst quisque. Lacus sed turpis tincidunt id aliquet. Risus ultricies tristique nulla aliquet enim tortor. Sed nisi lacus sed viverra tellus in hac habitasse. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Vulputate odio ut enim blandit volutpat. Volutpat lacus laoreet non curabitur gravida arcu ac. Maecenas pharetra convallis posuere morbi leo. Duis tristique sollicitudin nibh sit amet commodo nulla.
Sem integer vitae justo eget magna fermentum iaculis. Lectus quam id leo in vitae turpis. Ut tortor pretium viverra suspendisse. Lacinia at quis risus sed vulputate odio. Est pellentesque elit ullamcorper dignissim cras tincidunt. Sodales ut eu sem integer vitae justo. Urna nunc id cursus metus aliquam eleifend mi. Aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum. Id nibh tortor id aliquet lectus proin. Volutpat sed cras ornare arcu dui vivamus arcu. Turpis in eu mi bibendum neque egestas congue. Consequat interdum varius sit amet mattis vulputate enim nulla. Porta lorem mollis aliquam ut. Nisl nisi scelerisque eu ultrices vitae. Sed euismod nisi porta lorem mollis aliquam.
Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Tempus urna et pharetra pharetra massa massa ultricies. A erat nam at lectus urna. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vitae tempus quam pellentesque nec nam aliquam sem et. Non diam phasellus vestibulum lorem sed. Tincidunt lobortis feugiat vivamus at augue. In fermentum posuere urna nec. Ut venenatis tellus in metus vulputate eu scelerisque felis. Sit amet justo donec enim diam vulputate ut pharetra sit. Tempor id eu nisl nunc. Egestas quis ipsum suspendisse ultrices.
Eget magna fermentum iaculis eu non diam phasellus. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Sed nisi lacus sed viverra. Sem et tortor consequat id porta nibh venenatis cras sed. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. Pharetra convallis posuere morbi leo urna. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Justo donec enim diam vulputate. At lectus urna duis convallis convallis tellus id interdum velit. Donec adipiscing tristique risus nec feugiat in fermentum. In nulla posuere sollicitudin aliquam ultrices. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Cursus mattis molestie a iaculis at. Sed augue lacus viverra vitae. Viverra accumsan in nisl nisi scelerisque eu ultrices.
Morbi blandit cursus risus at ultrices mi. In eu mi bibendum neque egestas. Consectetur purus ut faucibus pulvinar. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Vel risus commodo viverra maecenas accumsan. Lacus luctus accumsan tortor posuere ac ut. Amet luctus venenatis lectus magna fringilla urna. Nulla malesuada pellentesque elit eget gravida cum. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Ullamcorper sit amet risus nullam eget felis eget nunc. In massa tempor nec feugiat nisl pretium fusce id. Integer feugiat scelerisque varius morbi. Fermentum et sollicitudin ac orci phasellus. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Purus semper eget duis at. Id porta nibh venenatis cras sed felis eget velit. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Lacus vestibulum sed arcu non odio. Ultrices eros in cursus turpis massa tincidunt dui ut.
Eu volutpat odio facilisis mauris sit amet massa vitae. Sodales neque sodales ut etiam sit amet. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Proin libero nunc consequat interdum varius. Tempus egestas sed sed risus pretium. Pellentesque habitant morbi tristique senectus et netus. Volutpat est velit egestas dui. Lacinia quis vel eros donec ac odio tempor orci dapibus. Fermentum odio eu feugiat pretium nibh ipsum. Feugiat vivamus at augue eget arcu dictum varius. Blandit cursus risus at ultrices. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Condimentum mattis pellentesque id nibh. Id diam vel quam elementum pulvinar etiam non. Pretium lectus quam id leo in vitae turpis massa. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non.
Dolor morbi non arcu risus quis varius quam quisque. Vitae nunc sed velit dignissim sodales. Vulputate odio ut enim blandit volutpat. Cursus sit amet dictum sit amet justo donec. Lectus nulla at volutpat diam ut venenatis tellus in. Nullam ac tortor vitae purus faucibus ornare suspendisse. Tincidunt eget nullam non nisi. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Eu nisl nunc mi ipsum. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Dui vivamus arcu felis bibendum ut tristique et egestas. Turpis nunc eget lorem dolor. Consequat interdum varius sit amet mattis vulputate. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Volutpat blandit aliquam etiam erat velit.
Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Scelerisque in dictum non consectetur a. Sagittis id consectetur purus ut faucibus pulvinar. Arcu non odio euismod lacinia at quis. Massa massa ultricies mi quis hendrerit dolor magna. Nibh ipsum consequat nisl vel pretium lectus quam id. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Lorem donec massa sapien faucibus et molestie ac. Sed ullamcorper morbi tincidunt ornare massa. Egestas dui id ornare arcu odio ut sem nulla pharetra. Duis at consectetur lorem donec massa sapien. Sit amet cursus sit amet dictum sit amet. Massa ultricies mi quis hendrerit. Quis auctor elit sed vulputate mi. Sapien nec sagittis aliquam malesuada bibendum arcu. Mauris vitae ultricies leo integer. Massa ultricies mi quis hendrerit dolor magna eget est. Ullamcorper sit amet risus nullam eget felis. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Viverra orci sagittis eu volutpat odio facilisis mauris.
Sed viverra ipsum nunc aliquet bibendum enim facilisis. Nibh praesent tristique magna sit amet. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Sem nulla pharetra diam sit amet nisl. Feugiat in fermentum posuere urna nec tincidunt praesent. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Elit ullamcorper dignissim cras tincidunt lobortis. Bibendum neque egestas congue quisque egestas. Ac tortor dignissim convallis aenean et tortor at risus. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Arcu non odio euismod lacinia at quis. Amet aliquam id diam maecenas ultricies mi eget. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Ante metus dictum at tempor commodo ullamcorper a. Id porta nibh venenatis cras sed. Pharetra magna ac placerat vestibulum lectus. Nulla aliquet porttitor lacus luctus accumsan tortor. Risus feugiat in ante metus.
Ac turpis egestas sed tempus urna et pharetra pharetra. Sagittis vitae et leo duis ut diam quam. Nisi scelerisque eu ultrices vitae auctor eu augue. Id volutpat lacus laoreet non. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Pulvinar neque laoreet suspendisse interdum consectetur libero. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Quis blandit turpis cursus in.
          </p>
      </div>
      <FileButton name="Upload" cls={styles.uploadButton} content={contentRef}/>
      <Button name="Play" cls={styles.playButton} onClickHandler={playButtonClick}/>
      <DownloadButton name="Download Transcript" cls={styles.downloadButton} content={contentRef}/>
      
      </div>
  )
}
